// Headless renderer for an animated sequence, for the clip in the README.
//
// Screen-recording the interactive engine would capture whatever the window
// system was doing that second -- under WSL that is a software GL stack -- and
// nothing in the recording would be reproducible. This renders the frames
// instead, at whatever rate the GPU manages, and the encoder in
// tools/make_clip.py turns them into a video. Same reasoning as capture_scene
// and the stills: a figure should be regenerated by a command.
//
// Frames are written as <prefix>_NNNN.tga, numbered from START so several runs
// can fill one sequence.
//
//   MODE=orbit|sweep    what to animate                    (default orbit)
//   FRAMES=n            how many frames this run writes    (default 120)
//   START=n             first frame number                 (default 0)
//   ENV=path.hdr        equirectangular environment
//   EXPOSURE=f          linear multiplier before the curve (default 1)
//   SCALE=f             scale every loaded node            (default 1)
//   ZOOM=f              add to the camera distance         (default 0)
//   PITCH=f             camera pitch, radians              (default 0)
//   LIGHT=x,y,z         directional light, world space
//   INTENSITY=f         light intensity
//   SSAA=1|2|4          supersampling factor               (default 2)
//   METALLIC=f          fixed metallic, orbit mode only    (default 0)
//   ROUGHNESS=f         fixed roughness, orbit mode only   (default 0.3)
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <sstream>
#include <iomanip>
#include <string>
#include <vector>
#include "Engine.h"
#include "compat.h"

// the pre-port Engine.h pulls in shaders.h, which declares these extern
Model *model = NULL;
Vec3f light_dir(1, 1, 1);

static int envVec(const char *name, float *out, int n)
{
    const char *s = getenv(name);
    if (!s) return 0;
    int got = 0;
    while (got < n && *s)
    {
        out[got++] = (float)atof(s);
        const char *comma = strchr(s, ',');
        if (!comma) break;
        s = comma + 1;
    }
    return got;
}

static float envFloat(const char *name, float fallback)
{
    const char *s = getenv(name);
    return s ? (float)atof(s) : fallback;
}

int main(int argc, char **argv)
{
    if (argc < 3)
    {
        printf("usage: %s out_prefix model.obj [model.obj ...]\n", argv[0]);
        return 2;
    }
    setenv("SDL_VIDEODRIVER", "dummy", 1);
    setenv("SDL_RENDER_DRIVER", "software", 1);

    Engine engine(1024, 768, 800, 800);
    if (!engine.init()) { printf("init failed\n"); return 1; }

    for (int i = 2; i < argc; i++)
        if (!engine.loadModel(argv[i])) printf("could not load %s\n", argv[i]);

    if (getenv("SCALE"))
    {
        float s = (float)atof(getenv("SCALE"));
        std::vector<SceneNode *> meshes;
        engine.getScene().getAllMeshNodes(meshes);
        for (SceneNode *n : meshes) n->setScale(Vec3f(s, s, s));
    }

    if (getenv("SSAA")) engine.setSSAA(atoi(getenv("SSAA")));

    float l[3];
    if (envVec("LIGHT", l, 3) == 3)
    {
        engine.getScene().light.direction = Vec3f(l[0], l[1], l[2]).normalize();
        light_dir = engine.getScene().light.direction;
    }
    if (getenv("INTENSITY"))
        engine.getScene().light.intensity = (float)atof(getenv("INTENSITY"));

    if (const char *env = getenv("ENV"))
    {
        engine.loadEnvironment(env);
        if (!engine.getScene().environment) printf("could not load %s\n", env);
    }
    if (getenv("EXPOSURE")) engine.setExposure((float)atof(getenv("EXPOSURE")));

    if (getenv("ZOOM")) engine.zoomCamera(envFloat("ZOOM", 0.f));
    engine.orbitCamera(0.f, envFloat("PITCH", 0.f));

    const std::string mode = getenv("MODE") ? getenv("MODE") : "orbit";
    const int frames = (int)envFloat("FRAMES", 120.f);
    const int start = (int)envFloat("START", 0.f);
    const bool orbit = (mode != "sweep");

    // A full turn spread over the run, applied one step at a time because
    // orbitCamera is relative. Doing it this way rather than setting an
    // absolute angle keeps whatever pitch was dialled in above.
    const float step = 2.0f * 3.14159265358979f / (float)frames;

    if (orbit)
    {
        engine.setMetallic(envFloat("METALLIC", 0.f));
        engine.setRoughness(envFloat("ROUGHNESS", 0.3f));
    }

    for (int f = 0; f < frames; f++)
    {
        if (orbit)
        {
            engine.orbitCamera(step, 0.f);
        }
        else
        {
            // Still turning, a quarter as fast. A sweep on a locked camera
            // reads as the video having frozen, and the reflection moving is
            // half of what makes a metal look like one.
            engine.orbitCamera(step * 0.25f, 0.f);

            // Two halves. First the surface goes from dielectric to metal at a
            // fixed low roughness, which is where the change reads most
            // clearly; then roughness opens up on the metal, which is what the
            // prefiltered environment levels are for.
            float t = (float)f / (float)(frames - 1);
            if (t < 0.5f)
            {
                engine.setMetallic(t * 2.0f);
                engine.setRoughness(0.12f);
            }
            else
            {
                engine.setMetallic(1.0f);
                engine.setRoughness(0.12f + (t - 0.5f) * 2.0f * 0.78f);
            }
        }

        engine.update();
        engine.render();

        std::ostringstream name;
        name << argv[1] << "_" << std::setfill('0') << std::setw(4)
             << (start + f) << ".tga";
        engine.captureFrame(name.str());
    }

    printf("wrote %d frames from %d\n", frames, start);
    return 0;
}
